import Head from "next/head";

import { BigTable } from "~/components/big-table";

export default function Home() {
  return (
    <>
      <Head>
        <title>Big Table Example</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container flex min-h-screen flex-col items-center justify-center gap-2">
        <BigTable />
      </main>
    </>
  );
}
